on:
  pull_request:
    branches:
      - master
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install dependencies
        run: go mod download
      - name: Set up PostgreSQL
        run: docker-compose -f postgres.yaml up -d
      - name: Build
        run: go build -v
      - name: Run tests
        run: go test -v
      - name: Tear down PostgreSQL
        run: docker-compose -f postgres.yaml down

