on:
  push:
    branches:
      - master
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_DB_USERNAME: postgres
      APP_DB_PASSWORD: example
      APP_DB_NAME_TEST: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install dependencies
        run: go mod download
      - name: Set up PostgreSQL
        run: docker-compose -f postgres.yml up -d
      - name: Build
        run: go build -v
      - name: Run tests
        run: go test -v
      - name: Tear down PostgreSQL
        run: docker-compose -f postgres.yml down

